version: '3'


services:
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_HOST="127.0.0.1"
      - REDIS_PASSWORD="redis_pass"
      - REDIS_PORT=6379
#    volumes:
#      - /path/to/local/dаta:/root/redis
#      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    # КОСТЫЛЬ тк возникает ошибка auth
    command: redis-server --requirepass redis_pass
  backend:
    build: ./backend/
    env_file: ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=redis_pass
    depends_on:
      - redis
    ports:
      - "8000:8000"